import { useEffect, useMemo, useState } from "react";
import { Aperture, ArrowRight, CheckCircle, CirclesThreePlus, Clock, Command, Cube, FileText, FolderOpen, LinkSimple, ListChecks, MagnifyingGlass, Minus, Plus, ShieldCheck, Sparkle, SquaresFour, UsersThree, X } from "@phosphor-icons/react";

const objects = [
  { id: "artifact", label: "Verified artifact" }, { id: "sources", label: "Sources" },
  { id: "collaborators", label: "Collaborators" }, { id: "release", label: "Cybou 0.8 release" },
  { id: "commitments", label: "3 commitments" }, { id: "suggestion", label: "Mind suggestion" },
];

function IconButton({ label, children, onClick, active = false }) {
  return <button className={`icon-button ${active ? "active" : ""}`} aria-label={label} title={label} onClick={onClick}>{children}</button>;
}
function Card({ id, className = "", selected, onSelect, children }) {
  return <section className={`surface ${className} ${selected === id ? "selected" : ""}`} onClick={() => onSelect(id)} tabIndex="0" aria-label={objects.find((o) => o.id === id)?.label}>{children}</section>;
}
function AppHeader({ mode, setMode, menuOpen, setMenuOpen }) {
  return <header className="topbar">
    <button className="brand" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen}><span className="brand-mark"><Aperture weight="light" /></span><span>Living Canvas</span></button>
    <nav className="breadcrumb" aria-label="Workspace breadcrumb"><button>Cybou Workspace</button><ArrowRight /><button>Programs</button><ArrowRight /><button className="current">Cybou 0.8 release</button></nav>
    <div className="runtime"><span className="runtime-label"><span className="status-dot" />{mode === "local" ? "Local runtime" : "Remote session"}</span>
      <div className="mode-switch" role="group" aria-label="Runtime mode"><button className={mode === "local" ? "active" : ""} onClick={() => setMode("local")}>Local</button><button className={mode === "remote" ? "active" : ""} onClick={() => setMode("remote")}>Remote</button></div>
      <time>10:24</time><IconButton label="Open Cybou menu" onClick={() => setMenuOpen(!menuOpen)} active={menuOpen}><Aperture /></IconButton>
    </div>
    {menuOpen && <div className="system-menu" role="menu"><div className="menu-title"><span className="brand-mark small"><Aperture /></span><div><strong>Cybou</strong><small>{mode === "local" ? "All data stays local" : "Connected securely"}</small></div></div>
      <button><CirclesThreePlus />New artifact</button><button><ListChecks />New commitment</button><button><UsersThree />Invite collaborator</button><div className="menu-divider" /><button><SquaresFour />Canvas view</button><button><ShieldCheck />System status</button></div>}
  </header>;
}

export function App() {
  const [mode, setMode] = useState("local"); const [selected, setSelected] = useState("release");
  const [menuOpen, setMenuOpen] = useState(false); const [searchOpen, setSearchOpen] = useState(false);
  const [query, setQuery] = useState(""); const [zoom, setZoom] = useState(79); const [suggestionState, setSuggestionState] = useState("pending");
  useEffect(() => { const onKey = (e) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setSearchOpen(true); } if (e.key === "Escape") { setSearchOpen(false); setMenuOpen(false); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, []);
  const filtered = useMemo(() => objects.filter((o) => o.label.toLowerCase().includes(query.toLowerCase())), [query]);
  const applySuggestion = () => { setSuggestionState("added"); setSelected("commitments"); };
  return <main className="app-shell">
    <AppHeader mode={mode} setMode={setMode} menuOpen={menuOpen} setMenuOpen={setMenuOpen} />
    <div className="canvas" style={{ "--canvas-scale": zoom / 79 }} onClick={() => menuOpen && setMenuOpen(false)}>
      <div className="ambient-ring ring-one" /><div className="ambient-ring ring-two" />
      <div className="connection connection-a"><span>delivers</span></div><div className="connection connection-b"><span>validated by</span></div><div className="connection connection-c"><span>involves</span></div><div className="connection connection-d"><span>tracked by</span></div><div className="connection connection-e"><span>depends on</span></div>
      <Card id="artifact" className="artifact-card" selected={selected} onSelect={setSelected}><header><span className="section-icon success"><CheckCircle /></span><h2>Verified artifact</h2></header><div className="artifact-body"><span className="cube"><Cube weight="fill" /></span><div><strong>cybou-0.8.0.tar.zst</strong><small>SHA256: a3f2…9c7b</small></div></div><div className="pills"><span>Reproducible</span><span>Signed</span></div><footer>Build&nbsp; • &nbsp;10m ago&nbsp; <span className="status-dot" /> Local</footer></Card>
      <Card id="sources" className="sources-card" selected={selected} onSelect={setSelected}><header><span className="section-icon info"><FolderOpen /></span><h2>Sources</h2></header><ul><li><span>Design doc</span><small>v4</small></li><li><span>Changelog</span><small>v3</small></li><li><span>Test results</span><small>128</small></li><li><span>Threat model</span><small>v2</small></li><li><span>Dependencies</span><small>52</small></li></ul><footer><span>5 items</span><button>View all</button></footer></Card>
      <Card id="collaborators" className="collaborators-card" selected={selected} onSelect={setSelected}><header><span className="section-icon info"><UsersThree /></span><h2>Collaborators</h2></header>{[['AN','Ari N.','Owner'],['MK','Mina K.','Release lead'],['JL','Jonas L.','QA lead'],['PS','Priya S.','Security']].map(([initials,name,role], i) => <div className="person" key={name}><span className={`avatar avatar-${i}`}>{initials}</span><span>{name}</span><small>{role}</small></div>)}<button className="text-action"><UsersThree />Invite collaborator</button></Card>
      <Card id="release" className="release-card" selected={selected} onSelect={setSelected}><span className="release-spark"><Sparkle weight="fill" /></span><h1>Cybou 0.8 release</h1><p className="eyebrow"><span />Release plan</p><p className="description">Stable release with local-first guarantees,<br/>improved reliability, and rollback safety.</p><div className="progress-label"><span>Progress</span><strong>{suggestionState === "added" ? "74%" : "68%"}</strong></div><div className="progress"><span style={{ width: suggestionState === "added" ? "74%" : "68%" }} /></div><div className="release-meta"><div><small>Target</small><strong>May 30, 2026</strong></div><div><small>Owner</small><strong><span className="avatar avatar-0">AN</span>Ari N.</strong></div><div><small>State</small><strong className="success-text"><span className="status-dot" />On track</strong></div></div><div className="context-bar"><button><FolderOpen />Open</button><button><ListChecks />Plan</button><button className="active"><Sparkle />Mind</button><button><LinkSimple />Link</button><button aria-label="More actions">•••</button></div></Card>
      <Card id="commitments" className="commitments-card" selected={selected} onSelect={setSelected}><header><span className="section-icon success"><CheckCircle /></span><h2>{suggestionState === "added" ? "4 commitments" : "3 commitments"}</h2></header><ul><li><CheckCircle /><span>Complete test matrix</span><small>May 20</small></li><li><CheckCircle /><span>Security review</span><small>May 22</small></li><li><CheckCircle /><span>Docs & migration guide</span><small>May 26</small></li>{suggestionState === "added" && <li className="new"><Clock /><span>Rollback verification</span><small>Added now</small></li>}</ul><button className="text-action">View commitments <ArrowRight /></button></Card>
      <Card id="suggestion" className={`suggestion-card ${suggestionState}`} selected={selected} onSelect={setSelected}>{suggestionState === "pending" ? <><header><span className="mind-label"><Sparkle weight="fill" />Mind suggests</span><span className="impact">High impact</span></header><h2>Add rollback verification</h2><p>No rollback test detected in plan.<br/>Adds safety and release confidence.</p><div className="suggestion-actions"><button onClick={(e) => { e.stopPropagation(); setSelected("sources"); }}>Review evidence</button><button className="primary" onClick={(e) => { e.stopPropagation(); applySuggestion(); }}>Add to plan</button></div><footer>Source: test-results.json, design-doc.md</footer></> : <div className="success-message"><CheckCircle weight="fill" /><div><strong>Added to release plan</strong><small>Rollback verification is now tracked.</small></div><button onClick={(e) => {e.stopPropagation(); setSuggestionState("pending");}}>Undo</button></div>}</Card>
      <aside className="minimap" aria-label="Canvas minimap"><div className="mini-node m1"/><div className="mini-node m2"/><div className="mini-node m3"/><div className="mini-node m4"/><div className="mini-node m5"/><span className="mini-focus" /><div className="zoom-controls"><IconButton label="Zoom in" onClick={() => setZoom(Math.min(100, zoom + 7))}><Plus /></IconButton><IconButton label="Zoom out" onClick={() => setZoom(Math.max(65, zoom - 7))}><Minus /></IconButton></div><footer><span>{zoom}%</span><button onClick={() => setZoom(79)}>Reset</button></footer></aside>
      <button className="search-trigger" onClick={() => setSearchOpen(true)}><MagnifyingGlass /><span>Search or act…</span><kbd><Command />K</kbd></button><div className="system-nominal"><span className="status-dot" />All systems nominal</div>
    </div>
    {searchOpen && <div className="overlay" onMouseDown={() => setSearchOpen(false)}><div className="command-palette" onMouseDown={(e) => e.stopPropagation()}><div className="search-field"><MagnifyingGlass /><input autoFocus value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search objects or run an action…"/><button onClick={() => setSearchOpen(false)}><X /></button></div><p className="result-label">Canvas objects</p><div className="results">{filtered.map((o) => <button key={o.id} onClick={() => { setSelected(o.id); setSearchOpen(false); setQuery(""); }}><span>{o.id === "release" ? <Sparkle /> : o.id === "collaborators" ? <UsersThree /> : o.id === "artifact" ? <Cube /> : <FileText />}</span>{o.label}<ArrowRight /></button>)}</div><footer><span><kbd>↵</kbd>Select</span><span><kbd>esc</kbd>Close</span></footer></div></div>}
  </main>;
}
