// SPDX-FileCopyrightText: 2026 Cybou contributors
// SPDX-License-Identifier: MIT

//! Modular card and content components for CYBOU Living Canvas.

pub mod agents;
pub mod attention;
pub mod backup;
pub mod beliefs;
pub mod calendar;
pub mod capabilities;
pub mod cognitive_graph;
pub mod commitments;
pub mod contacts;
pub mod content;
pub mod context;
pub mod diff;
pub mod disclosure;
pub mod editor;
pub mod event_journal;
pub mod file_manager;
pub mod generic;
pub mod identity;
pub mod insight;
pub mod inspector;
pub mod journal;
pub mod journal_feed;
pub mod learning;
pub mod lifecycle;
pub mod mail;
pub mod meaning;
pub mod monitor;
pub mod network;
pub mod notes;
pub mod notifications;
pub mod operations;
pub mod outline;
pub mod packages;
pub mod perception;
pub mod processes;
pub mod security;
pub mod self_model;
pub mod services;
pub mod session;
pub mod shell;
pub mod storage;
pub mod system_logs;
pub mod updates;
pub mod user_settings;

pub use agents::{AgentsCard, AgentsContent};
pub use attention::{AttentionCard, AttentionContent};
pub use backup::BackupContent;
pub use beliefs::{BeliefsCard, BeliefsContent};
pub use calendar::CalendarContent;
pub use capabilities::{CapabilitiesCard, CapabilitiesContent};
pub use cognitive_graph::CognitiveGraphContent;
pub use commitments::{CommitmentsCard, CommitmentsContent};
pub use contacts::ContactsContent;
pub use content::CardContent;
pub use context::{ContextCard, ContextContent};
pub use diff::{DiffCard, DiffContent};
pub use disclosure::{DisclosureCard, DisclosureContent};
pub use editor::{EditorCard, EditorContent};
pub use event_journal::EventJournalContent;
pub use file_manager::{FileManagerCard, FileManagerContent};
pub use generic::GenericToolCard;
pub use identity::{IdentityCard, IdentityContent};
pub use insight::{InsightCard, InsightContent};
pub use inspector::{InspectorCard, InspectorContent};
pub use journal::{JournalCard, JournalContent};
pub use journal_feed::{JournalFeedCard, JournalFeedContent};
pub use learning::LearningContent;
pub use lifecycle::{LifecycleCard, LifecycleContent};
pub use mail::MailContent;
pub use meaning::MeaningContent;
pub use monitor::MonitorContent;
pub use network::NetworkContent;
pub use notes::NotesContent;
pub use notifications::NotificationsContent;
pub use operations::OperationsContent;
pub use outline::{OutlineCard, OutlineContent};
pub use packages::PackagesContent;
pub use perception::{PerceptionCard, PerceptionContent};
pub use processes::ProcessesContent;
pub use security::SecurityContent;
pub use self_model::{SelfModelCard, SelfModelContent};
pub use services::ServicesContent;
pub use session::{SessionCard, SessionContent};
pub use shell::{ShellCard, ShellContent};
pub use storage::StorageContent;
pub use system_logs::SystemLogsContent;
pub use updates::UpdatesContent;
pub use user_settings::UserSettingsContent;
