// SPDX-FileCopyrightText: 2026 Cybou contributors
// SPDX-License-Identifier: MIT
#include "LifecycleService.h"
#include "cybou/fabric/FabricCodec.h"
#include <QDir>
#include <QFile>
#include <QTemporaryDir>
#include <QTest>
using namespace cybou;
class TestLifecycle:public QObject{Q_OBJECT private Q_SLOTS:
void persistsAndRecoversActiveRun(){QTemporaryDir root;auto path=root.filePath("lifecycle/state.json");QUuid id;
 {LifecycleService s(path);QVERIFY(s.isReady());QVERIFY(s.Transition("idle"));LifecycleRun r;r.runId=QUuid::createUuid();id=r.runId;r.kind="consolidation";r.policyId="test";r.requestedAt=QDateTime::currentDateTimeUtc();QVERIFY(s.BeginRun(encodeLifecycleRun(r)));}
 {LifecycleService s(path);QVERIFY(s.isReady());QString e;auto state=FabricCodec::decodeMap(s.State(),&e);QVERIFY(e.isEmpty());QCOMPARE(state["mode"].toString(),QString("recovering"));QCOMPARE(state["runId"].toString(),id.toString(QUuid::WithoutBraces));QCOMPARE(state["status"].toString(),QString("active"));}}
void rejectsIllegalAndCorruptState(){QTemporaryDir root;auto path=root.filePath("state.json");LifecycleService s(path);QVERIFY(!s.Transition("consolidating"));QFile f(path);QVERIFY(f.open(QIODevice::WriteOnly|QIODevice::Truncate));f.write("{\"mode\":\"bogus\"}");f.close();LifecycleService broken(path);QVERIFY(!broken.isReady());}
void migratesLegacyAndRejectsFutureState(){QTemporaryDir root;auto path=root.filePath("state.json");QFile f(path);QVERIFY(f.open(QIODevice::WriteOnly));f.write("{\"mode\":\"awake\",\"run\":\"\"}");f.close();LifecycleService migrated(path);QVERIFY(migrated.isReady());QVERIFY(QFile::exists(path+".pre-v1"));QFile current(path);QVERIFY(current.open(QIODevice::ReadOnly));QVERIFY(current.readAll().contains("\"version\":1"));current.close();QVERIFY(current.open(QIODevice::WriteOnly|QIODevice::Truncate));current.write("{\"version\":99,\"mode\":\"awake\"}");current.close();LifecycleService future(path);QVERIFY(!future.isReady());QCOMPARE(future.startupError(),QString("unsupported lifecycle state version"));}
void workAcknowledgementsAreIdempotentAndGateCompletion(){QTemporaryDir root;LifecycleService s(root.filePath("state.json"));QVERIFY(s.Transition("idle"));auto id=s.RequestRun("consolidation","test",42,{"predictor"},{"workspace"});QVERIFY(!id.isEmpty());auto key=s.WorkOperationKey("predictor");QVERIFY(!key.isEmpty());QVERIFY(!s.AcknowledgeWork("predictor",key,41));QVERIFY(s.AcknowledgeWork("predictor",key,42));QVERIFY(s.AcknowledgeWork("predictor",key,42));QVERIFY(!s.FinishRun("completed","accepted"));QVERIFY(s.MarkMissing("workspace","optional owner unavailable"));QVERIFY(!s.MarkMissing("workspace","different cause"));QVERIFY(!s.FinishRun("completed","no durable owner result"));QVERIFY(s.FinishRun("interrupted","unit test cleanup"));QString e;auto state=FabricCodec::decodeMap(s.State(),&e);QVERIFY(e.isEmpty());QCOMPARE(state["mode"].toString(),QString("recovering"));QCOMPARE(state["completedWork"].toStringList(),QStringList{"predictor"});QCOMPARE(state["missingWork"].toStringList(),QStringList{"workspace"});QCOMPARE(state["missingCauses"].toMap().value("workspace").toString(),QString("optional owner unavailable"));}
void recoveryResumesSameOperationKey(){QTemporaryDir root;auto path=root.filePath("state.json");QString key;{LifecycleService s(path);QVERIFY(s.Transition("idle"));QVERIFY(!s.RequestRun("consolidation","test",7,{"predictor"},{}).isEmpty());key=s.WorkOperationKey("predictor");}{LifecycleService recovered(path);QVERIFY(recovered.isReady());QCOMPARE(recovered.WorkOperationKey("predictor"),key);QVERIFY(recovered.ResumeRun());QCOMPARE(recovered.WorkOperationKey("predictor"),key);QVERIFY(recovered.AcknowledgeWork("predictor",key,7));QVERIFY(!recovered.FinishRun("completed","unverified"));QVERIFY(recovered.FinishRun("interrupted","recovery test cleanup"));}}
void failedPersistenceRollsBackMemoryState(){QTemporaryDir root;const auto path=root.filePath("state.json");LifecycleService s(path);QVERIFY(s.Transition("idle"));QVERIFY(QFile::remove(path));QVERIFY(QDir().mkdir(path));LifecycleRun run;run.runId=QUuid::createUuid();run.kind="consolidation";run.policyId="rollback-test";run.requestedAt=QDateTime::currentDateTimeUtc();QVERIFY(!s.BeginRun(encodeLifecycleRun(run)));QString error;const auto state=FabricCodec::decodeMap(s.State(),&error);QVERIFY(error.isEmpty());QCOMPARE(state["mode"].toString(),QString("idle"));QVERIFY(!state["hasRun"].toBool());}
};QTEST_MAIN(TestLifecycle)
#include "tst_lifecycle.moc"
