# Copyright (c) 2026 Stanislav Saveliev
# SPDX-License-Identifier: Apache-2.0
"""Generate the compiled silhouette from Natural Earth's public-domain GeoJSON.

Usage: python tools/ui/generate_france_outline.py SOURCE.geojson
Source: https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_50m_admin_0_countries.geojson
This is an offline asset tool, never a runtime network request.
"""

import hashlib
import json
import math
from pathlib import Path
import sys


def simplify(points, tolerance):
    a, b = points[0], points[-1]
    dx, dy = b[0] - a[0], b[1] - a[1]
    length = dx * dx + dy * dy
    distances = []
    for x, y in points[1:-1]:
        t = max(0, min(1, ((x - a[0]) * dx + (y - a[1]) * dy) / length)) if length else 0
        distances.append(math.hypot(x - a[0] - t * dx, y - a[1] - t * dy))
    if not distances or max(distances) <= tolerance:
        return [a, b]
    split = distances.index(max(distances)) + 1
    return simplify(points[:split + 1], tolerance)[:-1] + simplify(points[split:], tolerance)


def main():
    source = Path(sys.argv[1]).read_bytes()
    feature = next(f for f in json.loads(source)['features'] if f['properties']['ADMIN'] == 'France')
    # Keep mainland and Corsica, excluding overseas territories and tiny islands.
    rings = [p[0] for p in feature['geometry']['coordinates']
             if len(p[0]) > 50 and all(-6 < x < 10 and 41 < y < 52 for x, y in p[0])]
    assert len(rings) == 2, 'Expected mainland France and Corsica'
    rings.sort(key=len, reverse=True)
    projected = [[(x * math.cos(math.radians(46.5)), -y) for x, y in ring] for ring in rings]
    xmin = min(x for ring in projected for x, y in ring)
    xmax = max(x for ring in projected for x, y in ring)
    ymin = min(y for ring in projected for x, y in ring)
    ymax = max(y for ring in projected for x, y in ring)
    lines = [
        '// Copyright (c) 2026 Stanislav Saveliev',
        '// SPDX-License-Identifier: Apache-2.0',
        '// Generated by tools/ui/generate_france_outline.py; do not edit points by hand.',
        '// Geometry: Natural Earth 1:50m admin-0 countries (public domain).',
        '// https://www.naturalearthdata.com/about/terms-of-use/',
        f'// Source SHA-256: {hashlib.sha256(source).hexdigest()}',
        '// Equirectangular projection at 46.5 degrees; simplified to 0.015 projected degrees.',
        '#ifndef CYBOU_QT_FRANCEOUTLINE_H', '#define CYBOU_QT_FRANCEOUTLINE_H',
        '#include <QPolygonF>', '', 'namespace CybouMap {',
        f'inline constexpr qreal ASPECT_RATIO = {(xmax - xmin) / (ymax - ymin):.8f};',
    ]
    for name, ring in zip(['MAINLAND', 'CORSICA'], projected):
        points = simplify(ring, 0.015)
        lines.append(f'inline const QPolygonF {name}' + '{')
        for x, y in points:
            lines.append(f'    QPointF{{{(x - xmin) / (xmax - xmin):.6f}, {(y - ymin) / (ymax - ymin):.6f}}},')
        lines.append('};')
        print(f'{name}: {len(points)} points')
    lines.extend(['} // namespace CybouMap', '#endif // CYBOU_QT_FRANCEOUTLINE_H', ''])
    target = Path(__file__).resolve().parents[2] / 'src/qt/franceoutline.h'
    output = '\n'.join(lines)
    if not target.exists() or target.read_text(encoding='utf-8') != output:
        target.write_text(output, encoding='utf-8')


if __name__ == '__main__':
    main()
